services:
  server:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/html
    restart: always
  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    env_file: "conf.env"
    depends_on:
      - db
    volumes:
      - wp-data:/var/www/html
    restart: always
  db:
    container_name: mariadb
    build: requirements/mariadb/
    env_file: "conf.env"
    volumes:
      - db-data:/var/lib/mysql
    restart: always

volumes:
  db-data:
  wp-data:

# add 127.0.0.1 mmoser.42.fr to /etc/hosts on virtual machine

