services:
  server:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/html
  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    env_file: "conf.env"
    depends_on:
      - db
    volumes:
      - wp-data:/var/www/html
  db:
    container_name: mariadb
    build: requirements/mariadb/
    env_file: "conf.env"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  wp-data:
