services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html/:ro
      - ../secrets/certificate/:/etc/ssl/certs/:ro
    restart: always
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
    restart: always
      - wp_data:/var/www/html/
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    environment:
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_USER_PASSWORD_FILE=/run/secrets/wp_user_password
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_ADMIN_PASSWORD_FILE=/run/secrets/wp_admin_password
      - WP_DB=${MARIADB_DATABASE}
      - WP_DB_PREFIX=${WP_DB_PREFIX}
      - WP_DB_HOST=mariadb
      - WP_DB_PORT=3306
      - WP_DB_USER=${MARIADB_USER}
      - WP_DB_PASSWORD_FILE=/run/secrets/db_password
      - WP_WEBSITE_URL=https://${DOMAIN_NAME}
      - WP_WEBSITE_TITLE=${WP_WEBSITE_TITLE}
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    volumes:
    restart: always
      - db_data:/var/lib/mysql/
    secrets:
      - db_password
      - db_root_password
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD_FILE=/run/secrets/db_password
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MARIADB_DATABASE=${MARIADB_DATABASE}
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mysql/
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress/
      o: bind

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

#TODO: add 127.0.0.1 mmoser.42.fr to /etc/hosts on virtual machine

